#FROM pgvector/pgvector:pg17
FROM solo-db

# Install pg_cron and other useful extensions
RUN apt-get update && apt-get install -y --no-install-recommends \
        postgresql-17-cron \
        postgresql-17-pgaudit \
        postgresql-17-wal2json \
        gettext-base \
    && rm -rf /var/lib/apt/lists/*

# Create directory for initialization scripts
RUN mkdir -p /docker-entrypoint-initdb.d/
